export const MOAT_PAGES = {
  "/moat": {
    title: "Moat Overview",
    eyebrow: "Foundation",
    description: "Collection readiness metrics for the Moat data layer.",
    body: "Track competitor coverage and provider readiness before any collection provider is connected.",
  },
  "/moat/competitors": {
    title: "Competitors",
    eyebrow: "Directory",
    description: "Manage competitor records and ingestion readiness fields.",
    body: "Manage competitor profile data before attaching review sources.",
  },
  "/moat/sources": {
    title: "Review Sources",
    eyebrow: "Source Registry",
    description: "Attach supported review sources to competitors.",
    body: "Manage source records only. No scraping or external provider calls are triggered here.",
  },
  "/moat/source-discovery": {
    title: "Source Discovery",
    eyebrow: "Source Identity",
    description: "Map exact source profiles and search patterns per competitor.",
    body: "Store source identity only. No external validation or collection calls are made.",
  },
  "/moat/providers": {
    title: "Providers",
    eyebrow: "Dry Run Registry",
    description: "Manage provider readiness without storing keys or making external calls.",
    body: "Provider records prepare Apify, Outscraper, and custom adapters for a future sprint.",
  },
  "/moat/test-sync": {
    title: "Test Sync",
    eyebrow: "Controlled POC",
    description: "Run the Scaler Google Maps review ingestion proof of concept.",
    body: "This page only allows Scaler + Google Maps and caps collection at 10 reviews.",
  },
  "/moat/jobs": {
    title: "Ingestion Jobs",
    eyebrow: "Job Tracking",
    description: "Track ingestion jobs, bulk review collection, and daily sync readiness.",
    body: "Run controlled review collection against active source profiles and monitor scrape job lifecycle.",
  },
  "/moat/reviews": {
    title: "Reviews",
    eyebrow: "Collected Reviews",
    description: "Inspect collected competitor reviews without analysis or mutation.",
    body: "Review records are read-only and sourced from competitor_reviews.",
  },
  "/moat/insights": {
    title: "Insights",
    eyebrow: "Review Intelligence",
    description: "Structured competitive intelligence derived from collected reviews.",
    body: "Read-only insight snapshots generated from review_analysis and competitor_insights.",
  },
  "/moat/opportunities": {
    title: "Opportunities",
    eyebrow: "Action Layer",
    description: "Actionable opportunities generated from stored Moat intelligence.",
    body: "Read-only opportunities derived from review analysis and competitor insight snapshots.",
  },
  "/moat/claims": {
    title: "Claims",
    eyebrow: "Moat v2",
    description: "Claims intelligence is intentionally deferred to Moat v2.",
    body: "Claims extraction and validation are not part of Moat v1. This route remains available for future continuity, but it is hidden from primary navigation until the Claims Engine is ready.",
  },
  "/moat/market-demand": {
    title: "Market Demand",
    eyebrow: "Demand Signals",
    description: "Recurring market demand signals generated from stored Moat intelligence.",
    body: "Read-only demand signals derived from review analysis, insight snapshots, and opportunity alignment.",
  },
  "/moat/reports": {
    title: "Reports",
    eyebrow: "Exports",
    description: "Founder-level executive reporting from all Moat intelligence layers.",
    body: "Read-only executive reports derived from reviews, insights, opportunities, alerts, and market demand.",
  },
  "/moat/alerts": {
    title: "Alerts",
    eyebrow: "Signal Monitor",
    description: "Important competitive signals generated from stored Moat intelligence.",
    body: "Read-only alerts derived from reviews, analysis, insights, and opportunities.",
  },
}
